services:
  # https://hub.docker.com/_/postgres

  postgres:
    image: postgres:16.3
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
    ports:
     - 15435:5432
    networks:
     - pgdata

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin  
      - ./scripts:/scripts 
    networks:
      - pgdata  
    restart: always
    depends_on:
    - postgres

networks:
  pgdata:

